export type CitySeedEntry = {
  slug: string;
  nameEn: string;
  nameUr: string;
  descriptionEn: string;
  descriptionUr: string;
  displayOrder: number;
};

function city(
  slug: string,
  nameEn: string,
  nameUr: string,
  displayOrder: number,
  regionEn: string,
  regionUr: string,
): CitySeedEntry {
  return {
    slug,
    nameEn,
    nameUr,
    descriptionEn: `Private excise facilitation support for ${nameEn}, ${regionEn}.`,
    descriptionUr: `${nameUr}، ${regionUr} کے لیے نجی ایکسائز سہولت۔`,
    displayOrder,
  };
}

function buildCities(
  regionEn: string,
  regionUr: string,
  entries: Array<{ slug: string; nameEn: string; nameUr: string }>,
): CitySeedEntry[] {
  return entries.map((entry, index) =>
    city(entry.slug, entry.nameEn, entry.nameUr, index + 1, regionEn, regionUr),
  );
}

export const CITY_SEED: Record<string, CitySeedEntry[]> = {
  punjab: buildCities("Punjab", "پنجاب", [
    { slug: "lahore", nameEn: "Lahore", nameUr: "لاہور" },
    { slug: "rawalpindi", nameEn: "Rawalpindi", nameUr: "راولپنڈی" },
    { slug: "faisalabad", nameEn: "Faisalabad", nameUr: "فیصل آباد" },
    { slug: "multan", nameEn: "Multan", nameUr: "ملتان" },
    { slug: "gujranwala", nameEn: "Gujranwala", nameUr: "گوجرانوالہ" },
    { slug: "sialkot", nameEn: "Sialkot", nameUr: "سیالکوٹ" },
    { slug: "sargodha", nameEn: "Sargodha", nameUr: "سرگودھا" },
    { slug: "bahawalpur", nameEn: "Bahawalpur", nameUr: "بہاولپور" },
    { slug: "sheikhupura", nameEn: "Sheikhupura", nameUr: "شیخوپورہ" },
    { slug: "rahim-yar-khan", nameEn: "Rahim Yar Khan", nameUr: "رحیم یار خان" },
    { slug: "jhang", nameEn: "Jhang", nameUr: "جھنگ" },
    { slug: "dera-ghazi-khan", nameEn: "Dera Ghazi Khan", nameUr: "ڈیرہ غازی خان" },
    { slug: "gujrat", nameEn: "Gujrat", nameUr: "گجرات" },
    { slug: "sahiwal", nameEn: "Sahiwal", nameUr: "ساہیوال" },
    { slug: "wah-cantt", nameEn: "Wah Cantt", nameUr: "واہ کینٹ" },
    { slug: "okara", nameEn: "Okara", nameUr: "اوکاڑہ" },
    { slug: "kasur", nameEn: "Kasur", nameUr: "قصور" },
    { slug: "chiniot", nameEn: "Chiniot", nameUr: "چنیوٹ" },
    { slug: "kamoke", nameEn: "Kamoke", nameUr: "کامونکے" },
    { slug: "hafizabad", nameEn: "Hafizabad", nameUr: "حافظ آباد" },
    { slug: "khanewal", nameEn: "Khanewal", nameUr: "خانیوال" },
    { slug: "muzaffargarh", nameEn: "Muzaffargarh", nameUr: "مظفر گڑھ" },
    { slug: "khushab", nameEn: "Khushab", nameUr: "خوشاب" },
    { slug: "mianwali", nameEn: "Mianwali", nameUr: "میانوالی" },
    { slug: "attock", nameEn: "Attock", nameUr: "اٹک" },
    { slug: "jhelum", nameEn: "Jhelum", nameUr: "جہلم" },
    { slug: "chakwal", nameEn: "Chakwal", nameUr: "چکوال" },
    { slug: "toba-tek-singh", nameEn: "Toba Tek Singh", nameUr: "ٹوبہ ٹیک سنگھ" },
    { slug: "vehari", nameEn: "Vehari", nameUr: "وہاڑی" },
    { slug: "lodhran", nameEn: "Lodhran", nameUr: "لودھراں" },
    { slug: "pakpattan", nameEn: "Pakpattan", nameUr: "پاکپتن" },
    { slug: "narowal", nameEn: "Narowal", nameUr: "نارووال" },
    { slug: "mandi-bahauddin", nameEn: "Mandi Bahauddin", nameUr: "منڈی بہاؤالدین" },
    { slug: "layyah", nameEn: "Layyah", nameUr: "لیہ" },
    { slug: "bhakkar", nameEn: "Bhakkar", nameUr: "بھکر" },
    { slug: "rajanpur", nameEn: "Rajanpur", nameUr: "راجن پور" },
  ]),
  islamabad: buildCities("Islamabad ICT", "اسلام آباد ICT", [
    { slug: "islamabad", nameEn: "Islamabad", nameUr: "اسلام آباد" },
  ]),
  sindh: buildCities("Sindh", "سندھ", [
    { slug: "karachi", nameEn: "Karachi", nameUr: "کراچی" },
    { slug: "hyderabad", nameEn: "Hyderabad", nameUr: "حیدرآباد" },
    { slug: "sukkur", nameEn: "Sukkur", nameUr: "سکھر" },
    { slug: "larkana", nameEn: "Larkana", nameUr: "لاڑکانہ" },
    { slug: "nawabshah", nameEn: "Nawabshah", nameUr: "نوابشاہ" },
    { slug: "mirpur-khas", nameEn: "Mirpur Khas", nameUr: "میرپورخاص" },
    { slug: "jacobabad", nameEn: "Jacobabad", nameUr: "جیکب آباد" },
    { slug: "shikarpur", nameEn: "Shikarpur", nameUr: "شکارپور" },
    { slug: "khairpur", nameEn: "Khairpur", nameUr: "خیرپور" },
    { slug: "dadu", nameEn: "Dadu", nameUr: "دادو" },
    { slug: "tando-adam", nameEn: "Tando Adam", nameUr: "ٹنڈو آدم" },
    { slug: "tando-allahyar", nameEn: "Tando Allahyar", nameUr: "ٹنڈو الہیار" },
    { slug: "badin", nameEn: "Badin", nameUr: "بدین" },
    { slug: "thatta", nameEn: "Thatta", nameUr: "ٹھٹہ" },
    { slug: "umerkot", nameEn: "Umerkot", nameUr: "عمرکوٹ" },
    { slug: "sanghar", nameEn: "Sanghar", nameUr: "سانگھڑ" },
    { slug: "ghotki", nameEn: "Ghotki", nameUr: "گھوٹکی" },
    { slug: "kashmore", nameEn: "Kashmore", nameUr: "کشمور" },
    { slug: "qambar-shahdadkot", nameEn: "Qambar Shahdadkot", nameUr: "قمبر شہداد کوٹ" },
    { slug: "matiari", nameEn: "Matiari", nameUr: "مٹیاری" },
    { slug: "jamshoro", nameEn: "Jamshoro", nameUr: "جامشورو" },
    { slug: "naushahro-feroze", nameEn: "Naushahro Feroze", nameUr: "نوشہرو فیروز" },
  ]),
  kpk: buildCities("Khyber Pakhtunkhwa", "خیبر پختونخوا", [
    { slug: "peshawar", nameEn: "Peshawar", nameUr: "پشاور" },
    { slug: "mardan", nameEn: "Mardan", nameUr: "مردان" },
    { slug: "swat", nameEn: "Swat", nameUr: "سوات" },
    { slug: "abbottabad", nameEn: "Abbottabad", nameUr: "ایبٹ آباد" },
    { slug: "mansehra", nameEn: "Mansehra", nameUr: "مانسہرہ" },
    { slug: "kohat", nameEn: "Kohat", nameUr: "کوہاٹ" },
    { slug: "bannu", nameEn: "Bannu", nameUr: "بنوں" },
    { slug: "dera-ismail-khan", nameEn: "Dera Ismail Khan", nameUr: "ڈیرہ اسماعیل خان" },
    { slug: "nowshera", nameEn: "Nowshera", nameUr: "نوشہرہ" },
    { slug: "charsadda", nameEn: "Charsadda", nameUr: "چارسدہ" },
    { slug: "haripur", nameEn: "Haripur", nameUr: "ہری پور" },
    { slug: "swabi", nameEn: "Swabi", nameUr: "صوابی" },
    { slug: "chitral", nameEn: "Chitral", nameUr: "چترال" },
    { slug: "dir", nameEn: "Dir", nameUr: "دیر" },
    { slug: "malakand", nameEn: "Malakand", nameUr: "ملاکنڈ" },
    { slug: "lakki-marwat", nameEn: "Lakki Marwat", nameUr: "لکی مروت" },
    { slug: "karak", nameEn: "Karak", nameUr: "کرک" },
    { slug: "hangu", nameEn: "Hangu", nameUr: "ھنگو" },
    { slug: "tank", nameEn: "Tank", nameUr: "ٹانک" },
    { slug: "battagram", nameEn: "Battagram", nameUr: "بٹگرام" },
    { slug: "shangla", nameEn: "Shangla", nameUr: "شانگلہ" },
    { slug: "buner", nameEn: "Buner", nameUr: "بونیر" },
    { slug: "kohistan", nameEn: "Kohistan", nameUr: "کوہستان" },
  ]),
  balochistan: buildCities("Balochistan", "بلوچستان", [
    { slug: "quetta", nameEn: "Quetta", nameUr: "کوئٹہ" },
    { slug: "gwadar", nameEn: "Gwadar", nameUr: "گوادر" },
    { slug: "khuzdar", nameEn: "Khuzdar", nameUr: "خضدار" },
    { slug: "turbat", nameEn: "Turbat", nameUr: "تربت" },
    { slug: "chaman", nameEn: "Chaman", nameUr: "چمن" },
    { slug: "sibi", nameEn: "Sibi", nameUr: "سبی" },
    { slug: "zhob", nameEn: "Zhob", nameUr: "ژوب" },
    { slug: "loralai", nameEn: "Loralai", nameUr: "لورالائی" },
    { slug: "dera-murad-jamali", nameEn: "Dera Murad Jamali", nameUr: "ڈیرہ مراد جمالی" },
    { slug: "naseerabad", nameEn: "Naseerabad", nameUr: "نصیر آباد" },
    { slug: "mastung", nameEn: "Mastung", nameUr: "مستونگ" },
    { slug: "kalat", nameEn: "Kalat", nameUr: "کلات" },
    { slug: "pishin", nameEn: "Pishin", nameUr: "پشین" },
    { slug: "killa-abdullah", nameEn: "Killa Abdullah", nameUr: "قلا عبداللہ" },
    { slug: "killa-saifullah", nameEn: "Killa Saifullah", nameUr: "قلا سیف اللہ" },
    { slug: "lasbela", nameEn: "Lasbela", nameUr: "لسبیلہ" },
    { slug: "panjgur", nameEn: "Panjgur", nameUr: "پنجگور" },
    { slug: "nushki", nameEn: "Nushki", nameUr: "نوشکی" },
    { slug: "jaffarabad", nameEn: "Jaffarabad", nameUr: "جعفر آباد" },
    { slug: "awaran", nameEn: "Awaran", nameUr: "آواران" },
    { slug: "barkhan", nameEn: "Barkhan", nameUr: "بارخان" },
    { slug: "musakhel", nameEn: "Musakhel", nameUr: "موسا خیل" },
    { slug: "harnai", nameEn: "Harnai", nameUr: "ہرنائی" },
  ]),
  ajk: buildCities("Azad Jammu & Kashmir", "آزاد جموں و کشمیر", [
    { slug: "muzaffarabad", nameEn: "Muzaffarabad", nameUr: "مظفرآباد" },
    { slug: "mirpur", nameEn: "Mirpur", nameUr: "میرپور" },
    { slug: "kotli", nameEn: "Kotli", nameUr: "کوٹلی" },
    { slug: "rawalakot", nameEn: "Rawalakot", nameUr: "راولا کوٹ" },
    { slug: "bagh", nameEn: "Bagh", nameUr: "باغ" },
    { slug: "bhimber", nameEn: "Bhimber", nameUr: "بھمبر" },
    { slug: "haveli", nameEn: "Haveli", nameUr: "حویلی" },
    { slug: "neelum", nameEn: "Neelum", nameUr: "نیلم" },
    { slug: "sudhanoti", nameEn: "Sudhanoti", nameUr: "سدھنوتی" },
    { slug: "poonch", nameEn: "Poonch", nameUr: "پونچھ" },
  ]),
  "gilgit-baltistan": buildCities("Gilgit-Baltistan", "گلگت بلتستان", [
    { slug: "gilgit", nameEn: "Gilgit", nameUr: "گلگت" },
    { slug: "skardu", nameEn: "Skardu", nameUr: "سکردو" },
    { slug: "hunza", nameEn: "Hunza", nameUr: "ہنزہ" },
    { slug: "ghizer", nameEn: "Ghizer", nameUr: "غذر" },
    { slug: "astore", nameEn: "Astore", nameUr: "استور" },
    { slug: "diamer", nameEn: "Diamer", nameUr: "دیامر" },
    { slug: "ghanche", nameEn: "Ghanche", nameUr: "گھانچے" },
    { slug: "shigar", nameEn: "Shigar", nameUr: "شگر" },
    { slug: "kharmang", nameEn: "Kharmang", nameUr: "کھرمنگ" },
    { slug: "nagar", nameEn: "Nagar", nameUr: "نگر" },
  ]),
};
