export type CitySeedEntry = {
  slug: string;
  nameEn: string;
  descriptionEn: string;
  displayOrder: number;
};

function city(
  slug: string,
  nameEn: string,
  displayOrder: number,
  regionEn: string): CitySeedEntry {
  return {
    slug,
    nameEn,
    descriptionEn: `Private excise facilitation support for ${nameEn}, ${regionEn}.`,
    displayOrder};
}

function buildCities(
  regionEn: string,
  entries: Array<{ slug: string; nameEn: string}>): CitySeedEntry[] {
  return entries.map((entry, index) =>
    city(entry.slug, entry.nameEn, index + 1, regionEn));
}

export const CITY_SEED: Record<string, CitySeedEntry[]> = {
  punjab: buildCities("Punjab", [
    { slug: "lahore", nameEn: "Lahore"},
    { slug: "rawalpindi", nameEn: "Rawalpindi"},
    { slug: "faisalabad", nameEn: "Faisalabad"},
    { slug: "multan", nameEn: "Multan"},
    { slug: "gujranwala", nameEn: "Gujranwala"},
    { slug: "sialkot", nameEn: "Sialkot"},
    { slug: "sargodha", nameEn: "Sargodha"},
    { slug: "bahawalpur", nameEn: "Bahawalpur"},
    { slug: "sheikhupura", nameEn: "Sheikhupura"},
    { slug: "rahim-yar-khan", nameEn: "Rahim Yar Khan"},
    { slug: "jhang", nameEn: "Jhang"},
    { slug: "dera-ghazi-khan", nameEn: "Dera Ghazi Khan"},
    { slug: "gujrat", nameEn: "Gujrat"},
    { slug: "sahiwal", nameEn: "Sahiwal"},
    { slug: "wah-cantt", nameEn: "Wah Cantt"},
    { slug: "okara", nameEn: "Okara"},
    { slug: "kasur", nameEn: "Kasur"},
    { slug: "chiniot", nameEn: "Chiniot"},
    { slug: "kamoke", nameEn: "Kamoke"},
    { slug: "hafizabad", nameEn: "Hafizabad"},
    { slug: "khanewal", nameEn: "Khanewal"},
    { slug: "muzaffargarh", nameEn: "Muzaffargarh"},
    { slug: "khushab", nameEn: "Khushab"},
    { slug: "mianwali", nameEn: "Mianwali"},
    { slug: "attock", nameEn: "Attock"},
    { slug: "jhelum", nameEn: "Jhelum"},
    { slug: "chakwal", nameEn: "Chakwal"},
    { slug: "toba-tek-singh", nameEn: "Toba Tek Singh"},
    { slug: "vehari", nameEn: "Vehari"},
    { slug: "lodhran", nameEn: "Lodhran"},
    { slug: "pakpattan", nameEn: "Pakpattan"},
    { slug: "narowal", nameEn: "Narowal"},
    { slug: "mandi-bahauddin", nameEn: "Mandi Bahauddin"},
    { slug: "layyah", nameEn: "Layyah"},
    { slug: "bhakkar", nameEn: "Bhakkar"},
    { slug: "rajanpur", nameEn: "Rajanpur"}]),
  islamabad: buildCities("Islamabad ICT", [
    { slug: "islamabad", nameEn: "Islamabad"}]),
  sindh: buildCities("Sindh", [
    { slug: "karachi", nameEn: "Karachi"},
    { slug: "hyderabad", nameEn: "Hyderabad"},
    { slug: "sukkur", nameEn: "Sukkur"},
    { slug: "larkana", nameEn: "Larkana"},
    { slug: "nawabshah", nameEn: "Nawabshah"},
    { slug: "mirpur-khas", nameEn: "Mirpur Khas"},
    { slug: "jacobabad", nameEn: "Jacobabad"},
    { slug: "shikarpur", nameEn: "Shikarpur"},
    { slug: "khairpur", nameEn: "Khairpur"},
    { slug: "dadu", nameEn: "Dadu"},
    { slug: "tando-adam", nameEn: "Tando Adam"},
    { slug: "tando-allahyar", nameEn: "Tando Allahyar"},
    { slug: "badin", nameEn: "Badin"},
    { slug: "thatta", nameEn: "Thatta"},
    { slug: "umerkot", nameEn: "Umerkot"},
    { slug: "sanghar", nameEn: "Sanghar"},
    { slug: "ghotki", nameEn: "Ghotki"},
    { slug: "kashmore", nameEn: "Kashmore"},
    { slug: "qambar-shahdadkot", nameEn: "Qambar Shahdadkot"},
    { slug: "matiari", nameEn: "Matiari"},
    { slug: "jamshoro", nameEn: "Jamshoro"},
    { slug: "naushahro-feroze", nameEn: "Naushahro Feroze"}]),
  kpk: buildCities("Khyber Pakhtunkhwa", [
    { slug: "peshawar", nameEn: "Peshawar"},
    { slug: "mardan", nameEn: "Mardan"},
    { slug: "swat", nameEn: "Swat"},
    { slug: "abbottabad", nameEn: "Abbottabad"},
    { slug: "mansehra", nameEn: "Mansehra"},
    { slug: "kohat", nameEn: "Kohat"},
    { slug: "bannu", nameEn: "Bannu"},
    { slug: "dera-ismail-khan", nameEn: "Dera Ismail Khan"},
    { slug: "nowshera", nameEn: "Nowshera"},
    { slug: "charsadda", nameEn: "Charsadda"},
    { slug: "haripur", nameEn: "Haripur"},
    { slug: "swabi", nameEn: "Swabi"},
    { slug: "chitral", nameEn: "Chitral"},
    { slug: "dir", nameEn: "Dir"},
    { slug: "malakand", nameEn: "Malakand"},
    { slug: "lakki-marwat", nameEn: "Lakki Marwat"},
    { slug: "karak", nameEn: "Karak"},
    { slug: "hangu", nameEn: "Hangu"},
    { slug: "tank", nameEn: "Tank"},
    { slug: "battagram", nameEn: "Battagram"},
    { slug: "shangla", nameEn: "Shangla"},
    { slug: "buner", nameEn: "Buner"},
    { slug: "kohistan", nameEn: "Kohistan"}]),
  balochistan: buildCities("Balochistan", [
    { slug: "quetta", nameEn: "Quetta"},
    { slug: "gwadar", nameEn: "Gwadar"},
    { slug: "khuzdar", nameEn: "Khuzdar"},
    { slug: "turbat", nameEn: "Turbat"},
    { slug: "chaman", nameEn: "Chaman"},
    { slug: "sibi", nameEn: "Sibi"},
    { slug: "zhob", nameEn: "Zhob"},
    { slug: "loralai", nameEn: "Loralai"},
    { slug: "dera-murad-jamali", nameEn: "Dera Murad Jamali"},
    { slug: "naseerabad", nameEn: "Naseerabad"},
    { slug: "mastung", nameEn: "Mastung"},
    { slug: "kalat", nameEn: "Kalat"},
    { slug: "pishin", nameEn: "Pishin"},
    { slug: "killa-abdullah", nameEn: "Killa Abdullah"},
    { slug: "killa-saifullah", nameEn: "Killa Saifullah"},
    { slug: "lasbela", nameEn: "Lasbela"},
    { slug: "panjgur", nameEn: "Panjgur"},
    { slug: "nushki", nameEn: "Nushki"},
    { slug: "jaffarabad", nameEn: "Jaffarabad"},
    { slug: "awaran", nameEn: "Awaran"},
    { slug: "barkhan", nameEn: "Barkhan"},
    { slug: "musakhel", nameEn: "Musakhel"},
    { slug: "harnai", nameEn: "Harnai"}]),
  ajk: buildCities("Azad Jammu & Kashmir", [
    { slug: "muzaffarabad", nameEn: "Muzaffarabad"},
    { slug: "mirpur", nameEn: "Mirpur"},
    { slug: "kotli", nameEn: "Kotli"},
    { slug: "rawalakot", nameEn: "Rawalakot"},
    { slug: "bagh", nameEn: "Bagh"},
    { slug: "bhimber", nameEn: "Bhimber"},
    { slug: "haveli", nameEn: "Haveli"},
    { slug: "neelum", nameEn: "Neelum"},
    { slug: "sudhanoti", nameEn: "Sudhanoti"},
    { slug: "poonch", nameEn: "Poonch"}]),
  "gilgit-baltistan": buildCities("Gilgit-Baltistan", [
    { slug: "gilgit", nameEn: "Gilgit"},
    { slug: "skardu", nameEn: "Skardu"},
    { slug: "hunza", nameEn: "Hunza"},
    { slug: "ghizer", nameEn: "Ghizer"},
    { slug: "astore", nameEn: "Astore"},
    { slug: "diamer", nameEn: "Diamer"},
    { slug: "ghanche", nameEn: "Ghanche"},
    { slug: "shigar", nameEn: "Shigar"},
    { slug: "kharmang", nameEn: "Kharmang"},
    { slug: "nagar", nameEn: "Nagar"}])};
