import { getTranslations } from "next-intl/server";

export async function getLegalPageEditorLabels() {
  const t = await getTranslations("admin.resources.legalPages.editor");

  return {
    slug: t("slug"),
    slugLockedNote: t("slugLockedNote"),
    titleEn: t("titleEn"),
    titleUr: t("titleUr"),
    excerptEn: t("excerptEn"),
    excerptUr: t("excerptUr"),
    contentEn: t("contentEn"),
    contentUr: t("contentUr"),
    contentHint: t("contentHint"),
    contentEditor: {
      write: t("contentEditor.write"),
      preview: t("contentEditor.preview"),
      previewEmpty: t("contentEditor.previewEmpty"),
      bold: t("contentEditor.bold"),
      heading2: t("contentEditor.heading2"),
      heading3: t("contentEditor.heading3"),
      link: t("contentEditor.link"),
      bulletList: t("contentEditor.bulletList"),
      orderedList: t("contentEditor.orderedList"),
      linkText: t("contentEditor.linkText"),
      linkUrl: t("contentEditor.linkUrl"),
      linkInsert: t("contentEditor.linkInsert"),
      linkCancel: t("contentEditor.linkCancel"),
      hint: t("contentHint"),
    },
    published: t("published"),
    active: t("active"),
    displayOrder: t("displayOrder"),
    save: t("save"),
    saved: t("saved"),
    saving: t("saving"),
    cancel: t("cancel"),
    seoTitle: t("seoTitle"),
    metaTitleEn: t("metaTitleEn"),
    metaTitleUr: t("metaTitleUr"),
    metaDescriptionEn: t("metaDescriptionEn"),
    metaDescriptionUr: t("metaDescriptionUr"),
    h1En: t("h1En"),
    h1Ur: t("h1Ur"),
    canonicalUrl: t("canonicalUrl"),
    ogTitleEn: t("ogTitleEn"),
    ogTitleUr: t("ogTitleUr"),
    ogDescriptionEn: t("ogDescriptionEn"),
    ogDescriptionUr: t("ogDescriptionUr"),
    ogImage: t("ogImage"),
    twitterCard: t("twitterCard"),
    robotsIndex: t("robotsIndex"),
    robotsFollow: t("robotsFollow"),
  };
}
