export async function getLegalPageEditorLabels() {
    return {
    slug: "Slug",
    slugLockedNote: "Canonical legal page URLs cannot be changed.",
    titleEn: "Page title (English)",
    excerptEn: "Short description (English)",
    contentEn: "Page content (English)",
    contentHint: "Use the toolbar for bold, headings, links, and lists. Separate paragraphs with a blank line. Preview shows how the public page will render.",
    contentEditor: {
      write: "Write",
      preview: "Preview",
      previewEmpty: "Nothing to preview yet. Add content in Write mode.",
      bold: "Bold",
      heading2: "Heading 2",
      heading3: "Heading 3",
      link: "Insert link",
      bulletList: "Bullet list",
      orderedList: "Numbered list",
      linkText: "Link text",
      linkUrl: "https://example.com",
      linkInsert: "Insert link",
      linkCancel: "Cancel",
      hint: "Use the toolbar for bold, headings, links, and lists. Separate paragraphs with a blank line. Preview shows how the public page will render."},
    published: "Published",
    active: "Active in footer",
    displayOrder: "Footer display order",
    save: "Save legal page",
    saved: "Legal page saved successfully.",
    saving: "Saving...",
    cancel: "Cancel",
    seoTitle: "SEO metadata",
    metaTitleEn: "Meta title (English)",
    metaDescriptionEn: "Meta description (English)",
    h1En: "H1 (English)",
    canonicalUrl: "Canonical URL",
    ogTitleEn: "OG title (English)",
    ogDescriptionEn: "OG description (English)",
    ogImage: "OG image URL",
    twitterCard: "Twitter card",
    robotsIndex: "Allow indexing",
    robotsFollow: "Allow following"};
}
