import "server-only";

import { getTranslations } from "next-intl/server";

export async function getLoginFormLabels() {
  const t = await getTranslations("auth.login");
  const tSocial = await getTranslations("auth.social");

  return {
    email: t("email"),
    password: t("password"),
    passwordHint: t("passwordHint"),
    invalidPassword: t("invalidPassword"),
    showPassword: t("showPassword"),
    signIn: t("signIn"),
    signingIn: t("signingIn"),
    signInFailed: t("signInFailed"),
    phone: t("phone"),
    phoneOrCnic: t("phoneOrCnic"),
    phoneHint: t("phoneHint"),
    phoneLoginHint: t("phoneLoginHint"),
    otp: t("otp"),
    otpHint: t("otpHint"),
    verifyOtp: t("verifyOtp"),
    verifyingOtp: t("verifyingOtp"),
    resendOtp: t("resendOtp"),
    changeEmail: t("changeEmail"),
    otpSentEmail: t("otpSentEmail"),
    accountNotFound: t("accountNotFound"),
    phoneAccountNotFound: t("phoneAccountNotFound"),
    accountExists: t("accountExists"),
    emailExists: t("emailExists"),
    phoneExists: t("phoneExists"),
    googleAccountExists: t("googleAccountExists"),
    signupPrompt: t("signupPrompt"),
    loginPrompt: t("loginPrompt"),
    loginLink: t("loginLink"),
    otpSentEmailSandbox: t("otpSentEmailSandbox"),
    otpSentEmailDevConsole: t("otpSentEmailDevConsole"),
    sendFailed: t("sendFailed"),
    verifyFailed: t("verifyFailed"),
    invalidEmail: t("invalidEmail"),
    invalidPhone: t("invalidPhone"),
    invalidIdentifier: t("invalidIdentifier"),
    methodEmail: t("methodEmail"),
    methodPhone: t("methodPhone"),
    forgotPassword: t("forgotPassword"),
    authError: t("authError"),
    noAccount: t("noAccount"),
    signupLink: t("signupLink"),
    orContinueWith: t("orContinueWith"),
    google: tSocial("google"),
    socialFailed: tSocial("failed"),
    socialNotConfigured: tSocial("notConfigured"),
  };
}

export async function getSignupFormLabels() {
  const t = await getTranslations("auth.signup");
  const tSocial = await getTranslations("auth.social");

  return {
    name: t("name"),
    email: t("email"),
    password: t("password"),
    confirmPassword: t("confirmPassword"),
    passwordHint: t("passwordHint"),
    passwordMismatch: t("passwordMismatch"),
    invalidPassword: t("invalidPassword"),
    showPassword: t("showPassword"),
    createAccount: t("createAccount"),
    creatingAccount: t("creatingAccount"),
    signupVerifyHint: t("signupVerifyHint"),
    phone: t("phone"),
    phoneHint: t("phoneHint"),
    cnic: t("cnic"),
    cnicHint: t("cnicHint"),
    cnicVerificationNote: t("cnicVerificationNote"),
    cnicExists: t("cnicExists"),
    invalidCnic: t("invalidCnic"),
    otp: t("otp"),
    otpHint: t("otpHint"),
    verifyOtp: t("verifyOtp"),
    verifyingOtp: t("verifyingOtp"),
    resendOtp: t("resendOtp"),
    changeEmail: t("changeEmail"),
    changePhone: t("changePhone"),
    otpSentEmail: t("otpSentEmail"),
    accountNotFound: t("accountNotFound"),
    accountExists: t("accountExists"),
    emailExists: t("emailExists"),
    phoneExists: t("phoneExists"),
    googleAccountExists: t("googleAccountExists"),
    signupPrompt: t("signupPrompt"),
    loginPrompt: t("loginPrompt"),
    signupLink: t("signupLink"),
    otpSentEmailSandbox: t("otpSentEmailSandbox"),
    otpSentEmailDevConsole: t("otpSentEmailDevConsole"),
    sendFailed: t("sendFailed"),
    verifyFailed: t("verifyFailed"),
    invalidEmail: t("invalidEmail"),
    invalidPhone: t("invalidPhone"),
    nameRequired: t("nameRequired"),
    methodEmail: t("methodEmail"),
    methodPhone: t("methodPhone"),
    hasAccount: t("hasAccount"),
    loginLink: t("loginLink"),
    orContinueWith: t("orContinueWith"),
    google: tSocial("google"),
    socialFailed: tSocial("failed"),
    authError: tSocial("failed"),
    socialNotConfigured: tSocial("notConfigured"),
  };
}
