export type SettingsPanelLabels = {
  tabs: {
    business: string;
    payment: string;
    seo: string;
    tracking: string;
    features: string;
  };
  save: string;
  saving: string;
  saved: string;
  error: string;
  secretsNote: string;
  business: {
    siteName: string;
    addressEn: string;
    globalSiteNote: string;
  };
  payment: {
    jazzCashInstructionsEn: string;
    easypaisaInstructionsEn: string;
    bankTransferInstructionsEn: string;
    paymentAccountDisplayName: string;
    manualPaymentEnabled: string;
    jazzCashGatewayEnabled: string;
    easypaisaGatewayEnabled: string;
    cardGatewayEnabled: string;
    gatewayPhase2Note: string;
    phase2Hint: string;
    methodsTitle: string;
    methodsEmpty: string;
    addMethod: string;
    removeMethod: string;
    methodLabel: string;
    methodNameEn: string;
    accountTitle: string;
    accountNumber: string;
    iban: string;
    methodInstructionsEn: string;
    methodActive: string;
    displayOrder: string;
  };
  seo: {
    defaultMetaTitleEn: string;
    defaultMetaDescriptionEn: string;
    defaultOgImage: string;
    defaultTwitterImage: string;
    canonicalDomain: string;
    sitemapEnabled: string;
    organizationName: string;
    organizationDescriptionEn: string;
    organizationLogoPath: string;
    organizationAreaServed: string;
    localBusinessName: string;
    localBusinessDescriptionEn: string;
    localBusinessPriceRange: string;
    localBusinessPriceRangeOptional: string;
    localBusinessAreaServed: string;
    localBusinessTelephone: string;
    localBusinessStreetAddress: string;
    localBusinessAddressLocality: string;
    localBusinessPostalCode: string;
    organizationSection: string;
    localBusinessSection: string;
  };
  tracking: {
    consentMode: string;
    requireConsentBeforeScripts: string;
    showConsentBanner: string;
    consentImplied: string;
    consentExplicit: string;
    consentDisabled: string;
    publicIdsNote: string;
  };
  features: {
    agentModuleEnabled: string;
    blogEnabled: string;
    reviewsEnabled: string;
    contactFormEnabled: string;
    submitRequestEnabled: string;
    floatingWhatsappEnabled: string;
    whatsappChannelEnabled: string;
    whatsappNotificationsEnabled: string;
    smsFallbackEnabled: string;
    maintenanceMode: string;
    maintenanceMessageEn: string;
  };
};
